#!/usr/bin/env python3
"""Entity index generator (capture-5, 2026-07-02): person/handle -> where in memory.

Answers "where do I know X from" in one lookup instead of 2-4 blind greps over 16
archive shards. Scans all memory files (active + shards + state files), extracts
person-name bigrams and @handles, and writes .claude/memory/ENTITY_INDEX.md:
entity | total mentions | files (with counts, most-mentioned first).

Generated, never hand-edited — same model as the archive indexes. Regenerated by
/consolidate Step 5. Read by /reply Step 1. Heuristic v1 (capitalized bigrams with a
stoplist); noise is acceptable in a lookup aid, silence is not.

Usage: entity_index.py [--min N]   (default min total mentions = 2)
"""
import pathlib, re, sys, collections

ROOT = pathlib.Path(__file__).resolve().parent.parent
MEM = ROOT / ".claude" / "memory"
OUT = MEM / "ENTITY_INDEX.md"

NAME_RE = re.compile(r"\b([A-Z][a-z]{2,}) ([A-Z][a-zà-ü]{2,})\b")
HANDLE_RE = re.compile(r"(?<![\w.])@([a-z][a-z0-9._-]{3,})\b")

# words that make a capitalized bigram NOT a person name (either position)
STOP = set("""Experience Hub Status Todo Agent Agents Adobe System Review Knowledge
Memory Meeting Notes Slack Confluence Claude Coworker Governance Content Discovery
Production Development Intelligence Stakeholder Map Project Folder State The This
Never Always One Many New Full Open Read Cloud Manager Service Services Workspace
Assistant Platform Enterprise Ground Truth North Star Quiet Hours Skills Skill
Prompt Library Unified Shell Brand Concierge Journal Quality Gate Key Files Home
Archive Index Access Sites Forms Assets Insights Search Data Lake Advisory Update
Updater Creator Technical Web Planning Working Session Sessions Report Reports
Reporting Modern Modernization Chat History Context Phase Plan Step Rule Rules
April May June July August March January February September October November
December Monday Tuesday Wednesday Thursday Friday Saturday Sunday Summit Board
Boards Card Cards Decision Decisions Group Groups Team Teams Test Tests Trial
Internal External Customer Customers Org Orgs Email Teams Live Next Last First
Second Third Big Small Todoist Grafana Splunk Databricks Langfuse Rubin Mithril
Fruitbar Quarry Onboarding Company Director Senior Product Note Level Draft Von
San Los Las Der Los""".split())


def main():
    min_total = int(sys.argv[sys.argv.index("--min") + 1]) if "--min" in sys.argv else 2
    files = sorted(MEM.glob("*.md")) + sorted((ROOT / ".claude").glob("state*.md"))
    per_entity = collections.defaultdict(collections.Counter)
    for f in files:
        if f.name in ("ENTITY_INDEX.md", "MEMORY.md"):
            continue
        txt = f.read_text()
        for a, b in NAME_RE.findall(txt):
            if a in STOP or b in STOP:
                continue
            per_entity[f"{a} {b}"][f.name] += 1
        for h in HANDLE_RE.findall(txt):
            per_entity[f"@{h}"][f.name] += 1

    rows = [(e, sum(c.values()), c) for e, c in per_entity.items()
            if sum(c.values()) >= min_total]
    rows.sort(key=lambda r: (-r[1], r[0]))

    lines = ["# Entity index — where people/handles appear in memory", "",
             "> GENERATED by `scripts/entity_index.py` — do not hand-edit. Regenerated by"
             " `/consolidate` Step 5. Lookup aid for `/reply` Step 1: find the files, then"
             " grep the entity there. Heuristic — some noise rows are expected; absence of"
             " a person you expect = grep manually and consider a glossary/stoplist fix.", "",
             f"_{len(rows)} entities (min {min_total} mentions) across {len(files)} files._", "",
             "| Entity | Total | Files (count) |", "|---|---|---|"]
    for e, total, c in rows:
        tops = ", ".join(f"`{n}`({k})" for n, k in c.most_common(6))
        more = f" +{len(c)-6} more" if len(c) > 6 else ""
        lines.append(f"| {e} | {total} | {tops}{more} |")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.name}: {len(rows)} entities from {len(files)} files")


if __name__ == "__main__":
    main()
